IMAGE_INSTALL += "kernel-module-tpm-i2c-infineon"
IMAGE_INSTALL += "infineon-tpm-hack"
IMAGE_INSTALL += "trousers"
IMAGE_INSTALL += "tpm-tools"
IMAGE_INSTALL += "tpm-quote-tools"
IMAGE_INSTALL += "strongswan"
IMAGE_INSTALL += "python-twisted"
IMAGE_INSTALL += "python-twisted-core"
IMAGE_INSTALL += "pcr-extend"
IMAGE_INSTALL += "pcr-calc"

